# Generated by Django 4.1.7 on 2023-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=70, verbose_name='Имя'),
        ),
    ]
